# Apache Geode
locator:
  image: apachegeode/geode:1.0.0-incubating.M2
  hostname: locator
  mem_limit: 512m
  expose:
   - "10334"
   - "1099"
   - "7575"
  ports:
   - "1099:1099"
   - "10334:10334"
   - "7575:7575"
   - "7070:7070"
  volumes:
   - ./apache.geode/:/scripts/
  command: /scripts/gfshWrapper.sh gfsh start locator --name=locator --mcast-port=0
#  command: /scripts/gfshWrapper.sh gfsh start locator --J="-Dgemfire.jmx-manager-hostname-for-clients=localhost" --hostname-for-clients=localhost --name=locator --mcast-port=0

server:
  image: apachegeode/geode:1.0.0-incubating.M2
  mem_limit: 2g
  links:
   - locator:locator
  expose:
   - "8080"
   - "40404"
   - "1099"
  ports:
   - "40404"
  volumes:
   - ./apache.geode/:/scripts/
  command: /scripts/startServer.sh --server-port=40404 --hostname-for-clients=localhost --max-heap=1G
  links:
   - locator

zookeeper:
  image:  kchen007/kafka
  expose:
   - "2181"
  ports:
   - "2181:2181"
  command: bin/zookeeper-server-start.sh config/zookeeper.properties

kafka:
  image: kchen007/kafka
  expose:
   - "9092"
  ports:
   - "9092:9092"
  links:
   - zookeeper
  command: bin/kafka-server-start.sh config/server.properties --override zookeeper.connect=zookeeper:2181

gateway:
   image: kchen007/gateway
   expose:
    - "8000"
   ports:
    - "8000:8000"
   links:
    - locator
    - server
    - kafka
   environment:
#    - GATEWAY_OPTS=-Dgeode.locator.name=locator
    - GATEWAY_OPTS=-DkafkaServers=kafka:9092 -Dgeode.locator.name=172.16.22.35

