# Apache Geode
locator:
  image: apachegeode/geode:1.0.0-incubating.M1
  hostname: locator
  mem_limit: 512m
  expose:
   - "10334"
   - "1099"
   - "7575"
  #  - "1024"
  ports:
   - "1099:1099"
   - "10334:10334"
   - "7575:7575"
   - "7070:7070"
  volumes:
   - ./apache.geode/:/scripts/
  command: /scripts/gfshWrapper.sh gfsh start locator --J="-Dgemfire.jmx-manager-hostname-for-clients=localhost" --hostname-for-clients=localhost --name=locator --mcast-port=0

server:
  image: apachegeode/geode:1.0.0-incubating.M1
  mem_limit: 2g
  links:
   - locator:locator
  expose:
   - "8080"
   - "40404"
   - "1099"
  ports:
   - "40404"
  volumes:
   - ./apache.geode/:/scripts/
   #- scripts/:/data/
  command: /scripts/startServer.sh --server-port=40404 --hostname-for-clients=192.168.99.100 --max-heap=1G

zookeeper:
  image:  kchen007/kafka
  expose:
   - "2181"
  ports:
   - "2181:2181"
  command: bin/zookeeper-server-start.sh config/zookeeper.properties

kafka:
  image: kchen007/kafka
  expose:
   - "9092"
  ports:
   - "9092:9092"
  volumes:
   - kafka_lib:/kafka_2.11-0.9.0.1/libs
  command: bin/kafka-server-start.sh config/server.properties

gateway:
   image: kchen007/gateway
   expose:
    - "8000"
   ports:
    - "8000:8000"
   volumes_from:
    - kafka:ro
   command: /bin/bash

