# Apache Geode
locator:
  image: apachegeode/geode:1.0.0-incubating.M2
#  hostname: 172.16.22.35
  mem_limit: 2048m
  expose:
   - "10334"
   - "1099"
   - "7575"
  ports:
   - "1099:1099"
   - "10334:10334"
   - "7575:7575"
   - "7070:7070"
  volumes:
   - ./apache.geode/:/scripts/
  command: /scripts/gfshWrapper.sh gfsh start locator --name=locator --mcast-port=0
#  command: /scripts/gfshWrapper.sh gfsh start locator --J="-Dgemfire.jmx-manager-hostname-for-clients=172.16.22.35" --hostname-for-clients=172.16.22.35 --name=locator --mcast-port=0

server:
  image: apachegeode/geode:1.0.0-incubating.M2
  mem_limit: 2g
  links:
   - locator:locator
  expose:
   - "8080"
   - "40404"
   - "1099"
  ports:
   - "40404"
  volumes:
   - ./apache.geode/:/scripts/
  links:
   - locator
  command: /scripts/startServer.sh --server-port=40404 --locators=locator[10334] --max-heap=1G
#  command: /scripts/startServer.sh --server-port=40404 --locators=locator[10334] --hostname-for-clients=172.16.22.35 --max-heap=1G

zookeeper:
  image:  kchen007/kafka
  expose:
   - "2181"
  ports:
   - "2181:2181"
  command: bin/zookeeper-server-start.sh config/zookeeper.properties

kafka:
  image: kchen007/kafka
  expose:
   - "9092"
  ports:
   - "9092:9092"
  links:
   - zookeeper
# when kafka return its connection information to client, it will use its hostname, in this case the container id
# if the client is not running within the composer, it cannot resolve the hostname. so we override the host name here with local ip 
# address
  command: bin/kafka-server-start.sh config/server.properties --override zookeeper.connect=zookeeper:2181 --override advertised.host.name=172.16.22.35

gateway:
   image: kchen007/gateway
   expose:
    - "8000"
   ports:
    - "8000:8000"
   links:
    - locator
    - server
    - kafka
   environment:
#    - GATEWAY_OPTS=-Dgeode.locator.name=locator
    - GATEWAY_OPTS=-DkafkaServers=kafka:9092 -Dgeode.locator.name=locator -Dgateway.hostname=172.16.22.35
   volumes:
    - ./kazzing.gateway/scripts/:/scripts/
   command: /scripts/startServer.sh 

cmdhandler:
  image: kchen007/cmdhandler 
  links:
# I have to add both locator and server as links, so that those host name can be seen in cmdhandler. otherwise
# it cannot publish to the cache
   - locator
   - server
   - kafka
  volumes:
   - ./cmdhandler/scripts/:/scripts/
  command: /scripts/startCmdHandler.sh kafka:9092 getFile locator 10334
